# Generated by Django 4.0.3 on 2022-03-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(default='address', max_length=100)),
                ('city', models.CharField(default='city', max_length=100)),
                ('zipcode', models.CharField(default=0, max_length=9)),
                ('landline', models.CharField(default=0, max_length=15)),
                ('cellularphone', models.CharField(default=0, max_length=15)),
                ('infected', models.BooleanField(default=False)),
            ],
        ),
    ]
