# Generated by Django 4.0.3 on 2022-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='landline',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to='records.user')),
            ],
        ),
    ]
