# Generated by Django 4.0.3 on 2022-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_user_landline_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='user',
        ),
        migrations.AddField(
            model_name='conditions',
            name='condition',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='conditions',
            field=models.ManyToManyField(to='records.conditions'),
        ),
    ]
