# Generated by Django 4.0.3 on 2022-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_remove_user_conditions_user_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='firstname', max_length=110),
        ),
    ]
