const isValidData = {
  firstname: { rgx: /^([a-zA-Z]+)?$/, message: "Not valid Name" },
  lastname: { rgx: /^([a-zA-Z]+)?$/, message: "Not valid Name" },
  address: { rgx: /^([a-zA-Z0-9\s,.'-]{3,})?$/, message: "Not valid address" },
  City: { rgx: /^([a-zA-Z]+)?$/, message: "please select from the dropdown" },
  zipcode: { rgx: /^(\d{5})?$/, message: "Not valid zip code" },
  landline: {
    rgx: /^([0-9]{10})?$/,
    message: "Not valid landline phone number",
  },
  cellularphone: {
    rgx: /^([0-9]{10})?$/,
    message: "Not valid cellular phone number",
  },
  dateofbirth: { rgx: /[0-9]/, message: "please select your date " },
};
const BACKEND = {
  ADDRESS: "http://127.0.0.1:8000",
};
const COLUMNS = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "firstname",
    headerName: "firstName",
   
  },
  { field: "lastname", headerName: "lastName" },
  {
    field: "dateofbirth",
    headerName: "dateOfBirth",
    
    type: "date",
  },
  { field: "address", headerName: "address", width: 150 },
  { field: "city", headerName: "city", width: 150 },
  { field: "zipcode", headerName: "zipCode" },
  {
    field: "cellularphone",
    headerName: "cellularphone",
    width: 150,
    allowResizing: true,
  },
  { field: "landline", headerName: "landline"},
  {
    field: "infected",
    headerName: "infected ? ",
    width: 80,
    type: "boolean",
  },
  {
    field: "conditions",
    headerName: "conditions ? ",
    width: 150,
    flex: 1,
    type: "array",
  },
];
const conditions = [
  { title: "*None" },
  { title: "Diabetes" },
  { title: "Heart Disease" },
  { title: "Stroke" },
  { title: "Tetanus" },
  { title: "Chickenpox" },
  { title: "Malaria" },
  { title: "Mumps" },
  { title: "Diphtheria" },
  { title: "High blood pressure" },
  { title: "Abnormal cholesterol levels" },
  {
    title: "Obesity ",
  },
];
const citysList = [
  { city: "Jerusalem" },
  { city: "Tel Aviv-Yafo" },
  { city: "Haifa" },
  { city: "Rishon LeẔiyyon" },
  { city: "Petaẖ Tiqwa" },
  { city: "Ashdod" },
  { city: "Netanya" },
  { city: "Beersheba" },
  { city: "Bené Beraq" },
  { city: "Holon" },
  { city: "Ramat Gan" },
  { city: "Ashqelon" },
  { city: "Reẖovot" },
  { city: "Bat Yam" },
  { city: "Bet Shemesh" },
  { city: "Kefar Sava" },
  { city: "Herẕliyya" },
  { city: "Hadera" },
  { city: "Modi‘in Makkabbim Re‘ut" },
  { city: "Nazareth" },
  { city: "Lod" },
  { city: "Ramla" },
  { city: "Ra‘ananna" },
  { city: "Rahat" },
  { city: "Nahariyya" },
  { city: "Givatayim" },
  { city: "Hod HaSharon" },
  { city: "Rosh Ha‘Ayin" },
  { city: "Qiryat Ata" },
  { city: "Umm el Faḥm" },
  { city: "Qiryat Gat" },
  { city: "Eilat" },
  { city: "Nes Ẕiyyona" },
  { city: "‘Akko" },
  { city: "El‘ad" },
  { city: "Ramat HaSharon" },
  { city: "Karmiel" },
  { city: "Afula" },
  { city: "Tiberias" },
  { city: "Eṭ Ṭaiyiba" },
  { city: "Qiryat Yam" },
  { city: "Qiryat Moẕqin" },
  { city: "Qiryat Bialik" },
  { city: "Qiryat Ono" },
  { city: "Or Yehuda" },
  { city: "Ma‘alot Tarshīḥā" },
  { city: "Ẕefat" },
  { city: "Dimona" },
  { city: "Tamra" },
  { city: "Netivot" },
  { city: "Sakhnīn" },
  { city: "Yehud" },
  { city: "Al Buţayḩah" },
  { city: "Al Khushnīyah" },
];

module.exports = { citysList, isValidData, BACKEND, conditions, COLUMNS };
